modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/Apollounknowndev/lithostitched/issues"
license = "MIT"

[[mods]]
    modId = "lithostitched"
    version = "${file.jarVersion}"
    displayName = "Lithostitched"
    logoFile = "pack.png"
    authors = "Apollo, SmellyModder"
    description = '''Library mod with new configurability and compatibility enhancements for worldgen.'''

[[dependencies.lithostitched]]
    modId = "forge"
    mandatory = true
    versionRange = "[48,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.lithostitched]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.2,1.21)"
    ordering = "NONE"
    side = "BOTH"
