# Project
version=1.2.2
group=dev.worldgen.lithostitched

# Common
minecraft_version=1.21

# Forge & Neoforge
neoforge_version=21.0.77-beta

# Fabric
fabric_version=0.100.6+1.21
fabric_loader_version=0.15.11

# Mod options
mod_name=Lithostitched
mod_id=lithostitched

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Update changelog
update_changelog=- Added a new structure type for adding additional spawn conditions to structures, see wiki for details.\n- Fixed biome modifications not syncing to the client.\n- Made a code tweak to allow datagen of Lithostitched's pool element types.