# Project
version=1.4.10
group=dev.worldgen.lithostitched

# Common
minecraft_version=1.21.6

# Neoforge
neoforge_version=21.6.0-beta

# Fabric
fabric_version=0.127.0+1.21.6
fabric_loader_version=0.16.13

# Mod options
mod_name=Lithostitched
mod_id=lithostitched

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Update changelog
update_changelog=View changes in the technical changelog [here](https://github.com/Apollounknowndev/lithostitched/wiki/Technical-Changelog).