# Project
version=1.3.0
group=dev.worldgen.lithostitched

# Common
minecraft_version=1.21

# Forge & Neoforge
neoforge_version=21.0.77-beta

# Fabric
fabric_version=0.100.6+1.21
fabric_loader_version=0.15.11

# Mod options
mod_name=Lithostitched
mod_id=lithostitched

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Update changelog
update_changelog=View changes in the technical changelog [here](https://github.com/Apollounknowndev/lithostitched/wiki/Technical-Changelog).