# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "lithostitched"
mod.name = "Lithostitched"
mod.group = "dev.worldgen.lithostitched"
mod.url = "https://modrinth.com/project/lithostitched"
mod.sources = "https://github.com/Apollounknowndev/lithostitched"
mod.description = "An expansive library mod with new configurability and compatibility enhancements for worldgen"
mod.version = "2.0.4"

deps.fabric_loader = "0.19.5"
loomx.loom_version = "1.17-SNAPSHOT"

["26.3"]
mod.mc_releases = ["26.3"]


[fabric."26.3"]
mod.mc_compat = ">=26.2"
deps.fabric_api = "0.160.5+26.3"
deps.mod_menu = "21.0.0-alpha.1"
deps.apollib = "1.2.4-fabric-26.3"


[neoforge."26.3"]
mod.mc_compat = "[26.3, 26.4)"
deps.neo_loader = "26.3.0.22-beta"
deps.apollib = "1.2.5-neoforge-26.3"