# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "lithostitched"
mod.name = "Lithostitched"
mod.group = "dev.worldgen.lithostitched"
mod.url = "https://modrinth.com/project/lithostitched"
mod.sources = "https://github.com/Apollounknowndev/lithostitched"
mod.description = "A library mod with new configurability and compatibility enhancements for worldgen"
mod.version = "2.0.0+beta1"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["26.3"]
mod.mc_releases = ["26.3"]


[fabric."26.3"]
mod.mc_compat = ">=26.2"
deps.fabric_api = "0.156.3+26.3"
deps.mod_menu = "21.0.0-alpha.1"
deps.apollib = "1.1.4-fabric-26.2"


[neoforge."26.2"]
mod.mc_compat = "[26.2, 26.3)"
deps.neo_loader = "26.2.0.52-beta"
deps.apollib = "1.1.4-neoforge-26.2"