# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "lithostitched"
mod.name = "Lithostitched"
mod.group = "dev.worldgen.lithostitched"
mod.url = "https://modrinth.com/project/lithostitched"
mod.sources = "https://github.com/Apollounknowndev/lithostitched"
mod.description = "A library mod with new configurability and compatibility enhancements for worldgen"
mod.version = "1.8.0+beta6"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["21.1"]
mod.mc_releases = ["1.21", "1.21.1"]

[fabric."21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
deps.fabric_api = "0.116.12+1.21.1"
deps.mod_menu = "11.0.3"
deps.apollib = "1.2.0-fabric-21.1"


[neoforge."21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
deps.neo_loader = "21.1.234"
deps.apollib = "1.2.0-neoforge-21.1"