license = "MIT"

modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Apollo"
description = "${description}"

iconFile = "pack.png"
#displayURL = "..."
#issueTrackerUrl = "..."

[[mixins]]
config = "lithostitched.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"